[tool.poetry]
name = "ldctl"
version = "0.1.0"
description = ""
authors = ["Mariusz Jurgielewicz <mordor@mail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
